name: CD

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to release'
        required: false

jobs:
  build:
    runs-on: windows-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      # Add your build steps here

  livraison:
    runs-on: windows-latest
    name: Livraison
    needs: [build]
    if: ${{ inputs.version != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Configure GIT
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create release
        run: npm version ${{ inputs.version }}

      - name: Push changes
        run: git push --follow-tags
